In [1]:
import pandas as pd

data = pd.read_csv("GRASP10.csv", sep=" ")
data

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

   avgTime  noAsignados
0  3.35756          398
1  3.38776          399
2  4.92174          397
3  4.91643          395
4  3.20058          398
5  3.00885          403
6  3.20749          395
7  5.43402          401
8  3.14244          398
9  3.57267          398

In [2]:
data.describe()

         avgTime  noAsignados
count  10.000000    10.000000
mean    3.814954   398.200000
std     0.904222     2.440401
min     3.008850   395.000000
25%     3.202307   397.250000
50%     3.372660   398.000000
75%     4.580490   398.750000
max     5.434020   403.000000